config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get 'movie/search', to: 'movies#search'
  resources :users, only: [:index, :show, :edit, :update]
  resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :movie_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum:100 }
  validates :genre, presence: true
  
  def self.search(search)
    if search != ""
      Movie.where(['title LIKE(?) OR genre LIKE(?)', "%#{search}%", "%#{search}%"])
    else 
      Movie.none
    end
  end
end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  validates :comment, presence: true, length: { maximum:50 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  
  has_many :movies, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true, length: { in: 1..20 }, uniqueness: true
  validates :introduction, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.new(movie_id: movie.id)
    favorite.save
    redirect_to movie_path(movie.id)
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.find_by(movie_id: movie.id)
    favorite.destroy
    redirect_to movie_path(movie.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/movie_comments_controller.rb
class MovieCommentsController < ApplicationController
  def create
    movie = Movie.find(params[:movie_id])
    @movie_comment = MovieComment.new(movie_comment_params)
    @movie_comment.user_id = current_user.id
    @movie_comment.movie_id = movie.id
    if @movie_comment.save
      redirect_to movie_path(movie.id)
    else
      @movie = Movie.find(params[:movie_id])
      @user = @movie.user
      render "movies/show"
    end
  end
  
  def destroy
    MovieComment.find_by(id: params[:id]).destroy
    redirect_to movie_path(params[:movie_id])
  end
  
  private
  def movie_comment_params
    params.require(:movie_comment).permit(:comment)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @movies = Movie.page(params[:page])
  end
  
  def search
    @user = User.find(current_user.id)
    @movies = Movie.search(params[:keyword]).page(params[:page])
    render :index
  end
  
  def show
    @movie = Movie.find(params[:id])
    @user = @movie.user
    @movie_comment = MovieComment.new
  end

  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to movie_path(@movie.id), notice: 'レビューを投稿しました。'
    else 
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
    if @movie.user_id != current_user.id
      redirect_to movies_path
    end
  end
  
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie.id), notice: 'レビューを更新しました。'
    else
      render :edit
    end
  end
  
  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to movies_path
  end
  
  private
  def movie_params
    params.require(:movie).permit(:title, :body, :genre)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movie_comments_helper.rb
module MovieCommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>
  <div class='container'>
    <div class='row'>
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>
          <i class="fas fa-film"></i>
          <strong>MovieTime</strong>へようこそ！
        </h1>
        <p>ここは映画のレビューサイトです。ログインまたは登録する必要があります。</p>
        <p>利用する際はデスクトップPCを推奨します。</p>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>
          <i class="fas fa-film"></i>
          <strong>MovieTime</strong>へようこそ！
        </h1>
        <p>In 
          <i class="fas fa-film"></i>
          <strong>MovieTime</strong>,
        </p>
        <p>ここでは映画のレビューを投稿したり、様々なジャンルの映画のレビューを見ることができます。</p>
        <p>より良い映画ライフにしましょう!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">ログイン</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">登録</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight 2023 Rei Suzuki</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>MovieTime</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="margin">
            <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
               <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li class="margin">
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li class="margin">
            <a class="nav-link text-light" href="/movies">
              <i class="fas fa-film"></i>Movies
            </a>
          </li>
          <li class="margin">
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li class="margin">
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li class="margin">
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li class="margin">
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li class="margin">
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background">
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2 class="font">映画のレビューを編集</h2></h2>
        <%= form_with model:@movie, local:true do |f| %>
          <% if @movie.errors.any? %>
            <h3><%= @movie.errors.count %> 件のエラーにより保存できませんでした:</h3>
            <ul>
              <% @movie.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :body, "レビュー" %>
            <%= f.text_area :body, class: "form-control-file" %>
          </div>
          <div class="form-group">
            <%= f.label :genre, "ジャンル" %>
            <%= f.select :genre, [["アクション", "アクション"], ["アドベンチャー", "アドベンチャー"], ["アニメ", "アニメ"], ["ファンタジー", "ファンタジー"], ["ミステリー", "ミステリー"], ["恋愛", "恋愛"], ["SF", "SF"], ["その他", "その他"]], include_blank: "選択して下さい" %>
          </div>
          <div class="form-group">
            <%= f.submit '更新', class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "見る", movie_path(@movie.id) %>　 | 　<%= link_to "戻る", movies_path %>
      </div>
    </div>
  </div>
</main>

app/views/movies/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'users/info', {user: @user} %>
      <div class="col-md-8 offset-md-1">
        <h2 class="font">映画一覧</h2>
        <%= form_with url: movie_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :keyword, placeholder: "タイトルまたはジャンル" %>
          <%= button_tag type: "submit", class: "btn-default" do %>
            <i class="fas fa-search">検索</i>
          <% end %>
        <% end %>
        <table class="table">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>レビュー</th>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @movies.each do |movie| %>
            <tr>
              <td><%= link_to movie.title, movie_path(movie.id) %></td>
              <td><%= movie.body.truncate(20) %></td>
              <td><%= movie.genre %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @movies %>
      </div>
    </div>
  </div>
</main>

app/views/movies/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2 class="font">映画のレビューを投稿</h2></h2>
        <%= form_with model:@movie, local:true do |f| %>
          <% if @movie.errors.any? %>
            <h3><%= @movie.errors.count %> 件のエラーにより保存できませんでした:</h3>
            <ul>
            <% @movie.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :body, "レビュー" %>
            <%= f.text_area :body, class: "form-control-file" %>
          </div>
          <div class="form-group">
            <%= f.label :genre, "ジャンル" %>
            <%= f.select :genre, [["アクション", "アクション"], ["アドベンチャー", "アドベンチャー"], ["アニメ", "アニメ"], ["ファンタジー", "ファンタジー"], ["ミステリー", "ミステリー"], ["恋愛", "恋愛"], ["SF", "SF"], ["その他", "その他"]], include_blank: "選択して下さい" %>
          </div>
          <div class="form-group">
            <%= f.submit '投稿', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/movies/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'users/info', {user: @user} %>
      <div class="col-md-8 offset-md-1">
        <h2 class="font">映画詳細</h2>
        <table class="table">
          <tbody>
            <tr>
              <td><%= @movie.title %></td>
              <td colspan="2"><%= @movie.body %></td>
              <td><%= @movie.genre %></td>
            </tr>
            <tr>
              <td>
                <% if @movie.user == current_user %>
                  <%= link_to "編集", edit_movie_path(@movie.id), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @movie.user == current_user %>
                  <%= link_to "削除", movie_path(@movie.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
              <td>
                <% if @movie.favorited_by?(current_user) %>
                  <p>
                    <%= link_to movie_favorites_path(@movie), method: :delete do %>
                      ♥<%= @movie.favorites.count %> いいね
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to movie_favorites_path(@movie), method: :post do %>
                      ♡<%= @movie.favorites.count %> いいね
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td><%= @movie.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
          </tbody>
        </table>
        <h3>投稿へのコメント</h3><p>コメント件数：<%= @movie.movie_comments.count %></p>
        <table class="table">
          <tbody>
            <% @movie.movie_comments.each do |movie_comment| %>
            <tr>
              <td><%= link_to movie_comment.user.name, user_path(movie_comment.user.id) %>さん</td>
              <td colspan="2"><%= movie_comment.comment %></td>
              <td>
                <%= movie_comment.created_at.strftime('%Y/%m/%d') %><br />
                <% if movie_comment.user == current_user %>
                <div>
                  <%= link_to "削除", movie_movie_comment_path(movie_comment.movie, movie_comment), method: :delete, "data-confirm" => "本当に消しますか？" %>
                </div>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <h4>コメントを投稿</h4>
        <% if @movie_comment.errors.any? %>
          <h3><%= @movie_comment.errors.count %> 件のエラーにより保存できませんでした:</h3>
          <ul>
          <% @movie_comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        <%= form_with(model:[@movie, @movie_comment], local: true) do |f| %>
        　<%= f.text_area :comment, rows:'3',placeholder: "コメントをここに" %>
        　<%= f.submit "投稿" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/_info.html.erb
<div class="col-md-3">
  <h2 class="font">ユーザー情報</h2>
  <table class="table">
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "default-image.jpg" %>
    </tr>
    <tr>
      <th>名前</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>紹介</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>　 
  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
    <%= link_to "レビューを投稿", new_movie_path, class: "btn btn-success btn-block" %>
  </div>
</div>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2 class="font">ユーザー情報を編集</h2>
        <%= form_with model:@user, local:true do |f| %>
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> 件のエラーにより保存できませんでした:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="form-group">
            <%= f.label :name, "名前" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, "イメージ" %>
            <%= f.attachment_field :profile_image, class: "form-control-file" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction, "紹介" %>
            <%= f.text_area :introduction, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit '更新', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'users/info', {user: @user} %>
      <div class="col-md-8 offset-md-1">
        <h2 class="font">ユーザー一覧</h2>
        <table class="table">
          <thead>
            <tr>
              <th>イメージ</th>
              <th>名前</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "default-image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "見る", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'users/info', {user: @user} %>
      <div class="col-md-8 offset-md-1">
        <h2 class="font">映画一覧</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>レビュー</th>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @movies.each do |movie| %>
            <tr>
              <td><%= link_to movie.title, movie_path(movie.id) %></td>
              <td><%= movie.body.truncate(20) %></td>
              <td><%= movie.genre %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>